# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Use Node.js {{matrix.node-version}}
      uses: actions/setup-node@v1.4.2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm install
      env:
        CI: true
    - name: npm lint
      run: |
        npm run lint
        npm run lint:style
      env:
        CI: true
    - name: Cypress run
      uses: cypress-io/github-action@v1
      with:
        browser: chrome
        headless: true
      env:
        VUE_APP_DASHBOARD_USER: ${{ secrets.VUE_APP_DASHBOARD_USER }}
        VUE_APP_TESTADMIN_USER: ${{ secrets.VUE_APP_TESTADMIN_USER }}
        VUE_APP_TESTADMIN_PASSWORD: ${{ secrets.VUE_APP_TESTADMIN_PASSWORD }}
        VUE_APP_TESTUSER_USER: ${{ secrets.VUE_APP_TESTUSER_USER }}
        VUE_APP_TESTUSER_PASSWORD: ${{ secrets.VUE_APP_TESTUSER_PASSWORD }}
        NODE_ENV: ${{ secrets.NODE_ENV }}
